put:
  x-eov-operation-id: transferDataTable
  x-eov-operation-handler: v1/handlers/data-tables/data-tables.handler
  tags:
    - DataTable
  summary: Transfer a data table to another project
  description: Transfer a data table to another project
  parameters:
    - $ref: '../schemas/parameters/dataTableId.yml'
  requestBody:
    description: Destination project information for the data table transfer.
    content:
      application/json:
        schema:
          type: object
          properties:
            destinationProjectId:
              type: string
              description: The ID of the project to transfer the data table to.
          required:
            - destinationProjectId
    required: true
  responses:
    '200':
      description: Operation successful.
    '400':
      $ref: '../../../../shared/spec/responses/badRequest.yml'
    '401':
      $ref: '../../../../shared/spec/responses/unauthorized.yml'
    '404':
      $ref: '../../../../shared/spec/responses/notFound.yml'
